// Application Version Information File

// This file is created automatically by the version.sh script whenever
// the project is built by Lazarus. Manual changes will be lost.

const
  { The default Free Pascal Compiler }
  FPC_VERSION='3.2.2';
  FPC_PLATFORM='darwin';
  FPC_TARGET='x86_64';

  { The Lazarus I.D.E }
  LAZARUS_VERSION='4.0';

  { Source & Subversion Last Changed Commit }
  SOURCE_VERSION='1.0.0';
  SOURCE_REVISION='8';
  SOURCE_URL='http://github.com/shidel/CpME';
  SOURCE_COMMIT='8e705c6b347f62ad9e2f9f36a690c53939830e8e';

  { Version Build Atributes } 
  BUILD_DEBUG=False;
  BUILD_PRERELEASE=True;
  BUILD_PATCHED=False;
  BUILD_PRIVATE=False;
  BUILD_SPECIAL=False;
  BUILD_DATE='2025-07-01 08:46:54';

  { General Application Information }
  APP_IDENTIFIER='com.company.';
  APP_VERSION='1.0.0';
  APP_BUILD='0';
  APP_YEAR='2025';

